import sqlalchemy as sa
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
import pandas as pd

# 1. The Dynamic Database Map (Reflection)
# We do NOT define the table structure in code. 
# We let SQLAlchemy read it directly from the database schema.

# (Using an in-memory SQLite engine for this example)
engine = sa.create_engine("sqlite:///:memory:") 

# -- MOCK SETUP -- 
# (Creating a dummy table just so the reflection works in this example)
with engine.begin() as conn:
    conn.exec_driver_sql(
        "CREATE TABLE users (id INTEGER PRIMARY KEY, full_name TEXT, user_age INTEGER, email_address TEXT)"
    )
# ----------------

# Create the automap base and reflect the database tables automatically
Base = automap_base()
Base.prepare(autoload_with=engine)

# Dynamically grab the 'users' table class generated by SQLAlchemy
# We didn't write this class, SQLAlchemy built it by looking at the DB!
UserTable = Base.classes.users


# 2. The Dynamic Data Loader (The "Relay")
# We load the Excel file and map headers dynamically without Pydantic

# A configuration dictionary to map Excel headers to Database columns dynamically.
# This could be loaded from a JSON file or another database table.
excel_to_db_mapping = {
    "Name": "full_name",
    "Age": "user_age",
    "Email Address": "email_address"
}

# Step A: Load the messy Excel
try:
    df = pd.read_excel("data/data.xlsx")
except FileNotFoundError:
    # Fallback to an empty dataframe for the example if the file doesn't exist
    df = pd.DataFrame(columns=["Name", "Age", "Email Address"])

db_instances = []

# Step B: Iterate and build instances dynamically
records = df.to_dict(orient='records')

for row in records:
    # 1. Translate Excel keys to DB keys based on our dynamic mapping
    db_ready_dict = {}
    for excel_col, value in row.items():
        if excel_col in excel_to_db_mapping:
            db_col_name = excel_to_db_mapping[excel_col]
            db_ready_dict[db_col_name] = value
            
    # 2. Dynamically instantiate the reflected UserTable
    # NOTE: We do NOT get Pydantic validation here! 
    # If age is negative or email is malformed, we won't know until the database throws an error.
    new_record = UserTable(**db_ready_dict)
    
    db_instances.append(new_record)


# Step C: Load to DB
with Session(engine) as session:
    session.add_all(db_instances)
    session.commit()
    
    # Just to prove it worked dynamically
    print(f"Dynamically inserted {len(db_instances)} rows into the DB!")
